package com.pankaj.mvm.dto;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;

@Getter
@Setter
public class MasterProductRequest {

    private String sku; // Optional: if blank, auto-generated by SKU utility

    @NotBlank(message = "Product title is required")
    private String title;

    private String description;

    @NotNull(message = "Category ID is required")
    private Long categoryId;

    @NotNull(message = "Admin Minimum Price is required")
    @DecimalMin(value = "0.01", message = "Min price must be greater than zero")
    private BigDecimal minPrice;

    @NotNull(message = "Admin MRP is required")
    @DecimalMin(value = "0.01", message = "MRP must be greater than zero")
    private BigDecimal mrp;
}